version: "3.10"

volumes:
  easyocr_models:

services:
  nginx:
    build: 
      context: ./nginx/
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - taipy
  taipy:
    build: 
      context: taipy
#    ports:
#      - "9090:9090"
    command: python main.py
  jupyter:
    build:
      context: ./jupyter
      dockerfile: Dockerfile
#    runtime: nvidia
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - driver: nvidia
#              count: all
#              capabilities: [gpu]
    ports:
      - "8888:8888"
    user: root
    environment:
      - CHOWN_HOME=yes
      - CHOWN_HOME_OPTS=-R
      - CHOWN_EXTRA=/EASYOCR
      - EASYOCR_MODULE_PATH=/EASYOCR
    volumes:
      # EITHER mount project root dir for access to .git inside jupyter
      #- ./:/home/jovyan
      # OR only mount notebook folder
      - ./jupyter/notebooks:/home/jovyan/jupyter/notebooks
      # store models here, so they are not downloaded only once
      - easyocr_models:/EASYOCR
    command: 
    - "start-notebook.sh"
    - "--NotebookApp.token="
    - "--notebook-dir=/home/jovyan/jupyter/"
